const ActionTypes = {
  LOADING_ALL_MEMBERS_FAILED: 'LOADING_ALL_MEMBERS_FAILED',
  LOADING_ALL_MEMBERS_SUCCEDED: 'LOADING_ALL_MEMBERS_SUCCEDED',
  START_LOADING_ALL_MEMBERS: 'START_LOADING_ALL_MEMBERS',
};

export default ActionTypes;
