const ActionTypes = {
  GO_TO_NEXT_PAGE: 'GO_TO_NEXT_PAGE',
  GO_TO_PREVIOUS_PAGE: 'GO_TO_PREVIOUS_PAGE',
  HIDE_SUGGESTION_BOX: 'HIDE_SUGGESTION_BOX',
  SET_SEARCH_RESULTS: 'SET_SEARCH_RESULTS',
  SET_SUGGESTIONS: 'SET_SUGGESTIONS',
  SHOW_SUGGESTION_BOX: 'SHOW_SUGGESTION_BOX',
};

export default ActionTypes;
